# Generated by Django 4.2.6 on 2023-10-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
