# Generated by Django 4.2.6 on 2023-10-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_slider_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='nombre',
            field=models.CharField(default='Plato Oriental', max_length=45, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
