# Generated by Django 4.2.6 on 2023-11-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_slider_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='prioridad',
            field=models.CharField(default='1', max_length=1, verbose_name='Prioridad'),
            preserve_default=False,
        ),
    ]
