# Generated by Django 4.2.6 on 2023-11-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_slider_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='prioridad',
            field=models.PositiveIntegerField(verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
    ]
