# Generated by Django 4.2.6 on 2023-11-21 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0008_alter_usuario_imagen'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='comunidad.usuario', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_apertura',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacion',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='tienda',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='comunidad.tienda', verbose_name='Tienda'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.pedido', verbose_name='Pedido #')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle_Pedido',
                'verbose_name_plural': 'Detalle_Pedidos',
            },
        ),
    ]
