# Generated by Django 4.2.6 on 2023-11-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_pedido_cliente_pedido_estado_pedido_fecha_apertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Descubre la auténtica esencia de la comida rápida en cada bocado. Nuestros platillos, preparados con maestría, ofrecen una explosión de sabores inigualables. Desde hamburguesas jugosas hasta crujientes papas fritas, cada opción de nuestro menú es una invitación a la indulgencia. ¡Sumérgete en una experiencia culinaria rápida pero deliciosa con nosotros!', verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
