# Generated by Django 4.2.6 on 2023-11-21 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0006_usuario_correo_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
